opossum_101 = { 'id':'opossum_101',
                'markers':  ['Body_ds1_crn',
                             'Body_ds2_int',
                             'Body_ds3_cdl',
                             'Body_vn1_crn',
                             'Body_vn2_int',
                             'Body_vn3_cdl',
                             'Scapula_acr',
                             'Scapula_spi',
                             'Scapula_vtb',
                             'Humerus_dpc',
                             'Humerus_ent',
                             'Humerus_ect',
                             'Ulna_olc',
                             'Ulna_int',
                             'Ulna_dst',
                             'Radius_prx',
                             'Radius_int',
                             'Radius_dst',
                             'Teres_maj_prx',
                             'Teres_maj_dst',
                             'Biceps_prx',
                             'Biceps_dst']
             }
